name: rc168
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  browser_launcher: ^1.1.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  firebase_core: ^2.25.4
  firebase_in_app_messaging: ^0.7.4+13
  firebase_messaging: ^14.7.16
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_fcm: ^1.2.1
  flutter_html: ^3.0.0-alpha.6
  flutter_launcher_icons: ^0.13.1
  flutter_line_sdk: ^2.3.6
  flutter_local_notifications: ^16.3.2
  flutter_responsive_framework: ^0.0.2
  flutter_web_browser: ^0.17.1
  font_awesome_flutter: ^10.6.0
  html: ^0.15.4
  local_auth: ^2.1.8
  path_provider: ^2.1.2
  responsive_sizer: ^3.3.1
  share_plus: ^8.0.3
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  text_responsive: ^1.2.1
  url_launcher: ^6.2.2
  web_browser: ^0.5.0
  webview_flutter: ^2.0.13
  webview_flutter_web: ^0.2.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpah_ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ic_launcher.png
    - .env
